flowchart TD
    A[Rectangle] --> B(Rounded)
    B --> C{Diamond}
    C --> D((Circle))
    C --> E([Stadium])
    C --> F[[Subroutine]]
    C --> G[(Cylinder)]
    C --> H>Asymmetric]
    C --> I{{Hexagon}}
